### ISSUE TITLE
Grammar check for Documentation

### ISSUE THREAD

**Issue by neizod** [neizod/polar#19]
Since I'm not a native speaker, I highly doubt that I write document with a lot of mistakes. Anyone up for fixing the grammar?

Right now the document has 3 pages:

- [x] Installation
- [x] Maintenance
- [x] Configuration

The (compiled) document can be found here: https://neizod.github.io/polar/docs/

The source for document is on `gh-pages` branch and can be found here: https://github.com/neizod/polar/tree/gh-pages/_docs

Please work on `gh-pages` branch.

**Comment by VilijaSan** [comment]
I'll create a pr for Maintenance :)
